-- SQL 1: Atualiza campo mes das postagens com base no planejamento 2026
-- Cliente alvo: eb9aa951-b915-4b09-9c34-072b56afe4e0
-- Fonte: levantamento_vcc_temas_objetivos_2026.xlsx (aba Levantamento_Temas)
BEGIN;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM clientes WHERE id = 'eb9aa951-b915-4b09-9c34-072b56afe4e0'::uuid) THEN
    RAISE EXCEPTION 'cliente_id % nao encontrado na tabela clientes', 'eb9aa951-b915-4b09-9c34-072b56afe4e0';
  END IF;
END $$;

CREATE TEMP TABLE tmp_vcc_meses_2026 (
  titulo text PRIMARY KEY,
  mes text NOT NULL
) ON COMMIT DROP;

INSERT INTO tmp_vcc_meses_2026 (titulo, mes) VALUES
  ('O que muda quando você é avaliado por uma equipe focada em valvopatias?', 'Banco'),
  ('X Estudos que revolucionaram o manejo das valvopatias', 'Banco'),
  ('O ponto de virada: por que fundamos o Valve Care Center?', 'Abril'),
  ('Como a tecnologia tem transformado os desfechos dos pacientes?', 'Maio'),
  ('Por que existem casos difíceis? (Uma reflexão sobre prevenção)', 'Banco'),
  ('A diferença entre tratar um diagnóstico e tratar uma pessoa', 'Banco'),
  ('O valor da nossa equipe multidisciplinar na sua saúde', 'Abril'),
  ('Medicina de precisão sem deixar de lado a humanidade', 'Banco'),
  ('De olho no ecocardiograma: você sabe como funciona?', 'Abril'),
  ('Procedimento X: por que foi indicado nesse caso?', 'Banco'),
  ('É assim que se faz uma reunião do Heart Team!', 'Maio'),
  ('Da consulta médica ao Heart Team: como uma conduta fica mais segura', 'Abril'),
  ('Segunda opinião em valvopatias é sempre necessária?', 'Maio'),
  ('Por que é importante obter uma segunda opinião em valvopatias?', 'Banco'),
  ('Por que a segunda opinião pode ser uma ato de cuidado', 'Banco'),
  ('O que faz um serviço ser de excelência?', 'Abril'),
  ('Como construir um serviço de excelência em valvopatias?', 'Banco'),
  ('O que queremos que você sinta ao sair da nossa consulta', 'Abril'),
  ('O cuidado não termina com o procedimento! (importância do pós-procedimento)', 'Maio'),
  ('Como se decide o "timing" de uma intervenção em doenças valvares?', 'Maio'),
  ('Tudo que acontece antes do seu procedimento', 'Abril'),
  ('Bastidores do maior congresso de valvopatias do mundo!', 'Banco'),
  ('O que nós fazemos que a IA não consegue fazer/nunca vai conseguir fazer', 'Banco'),
  ('22 de fevereiro - abra os olhos e proteja o coração! (Dia de conscientização sobre valvopatias)', 'Banco'),
  ('Profissionais de excelência + centro de alta tecnologia: uma oportunidade ÚNICA de atendimento', 'Banco'),
  ('Erros que podem custar caro: diagnósticos corretos, condutas inadequadas', 'Banco'),
  ('Meu caso é para tratamento cirúrgico ou percutâneo?', 'Banco'),
  ('X Problemas que não tinham solução, mas agora têm! Como a medicina evoluiu nos últimos anos', 'Banco'),
  ('Atendimento centrado no paciente: o que isso significa na prática?', 'Maio'),
  ('Muitas vezes o que assusta não é a DOENÇA, e sim as DÚVIDAS e INCERTEZAS!', 'Banco'),
  ('Por que a tecnologia de ponta pode ser a diferença entre um desfecho BOM e um EXCELENTE', 'Banco'),
  ('O que nos torna referência quando o assunto é válvula?', 'Maio'),
  ('Bastidores do Eco: estrutura da sala, equipamentos, 2D x 3D, Doppler, como faz o exame...', 'Banco'),
  ('Bastidores da hemodinâmica: sala, posicionamento do paciente, acesso, duração...', 'Banco'),
  ('Bastidores da cirurgia: centro cirúrgico, REPAI, quarto', 'Banco'),
  ('Bastidores dos exames: máquinas de TC/RM, sala de laudos', 'Banco'),
  ('Quizz básico para pacientes (quantas valvas no coração?; Quantos folhetos na mitral/na aórtica?)', 'Banco'),
  ('Quizz avançado sobre caso clínico (intervenção X tto clínico; quantificar gravidade...)', 'Banco'),
  ('Quizz sobre algum artigo relevante/diretriz em valvopatias', 'Banco'),
  ('Perguntas frequentes (tema: nossa equipe e agendamentos)', 'Abril'),
  ('"Válvula em 1 minuto" (série recorrente): dúvidas reais de pacientes/familiares/outros médicos', 'Maio'),
  ('"Dicionário em valvopatias" (série recorrente): explicando significados/termos importantes', 'Banco'),
  ('Quanto o laudo do Eco diz "leve" e você sente que leve não é: o que fazer?', 'Banco'),
  ('Aquele momento em que o paciente pergunta "não dá pra esperar um pouco?"', 'Banco'),
  ('"Mas Dra., eu não tenho sopro no coração. Tenho mesmo problema na válvula?"', 'Junho'),
  ('Quem tem valvopatias pode: fazer academia? viajar de avião? tomar diurético?....', 'Junho'),
  ('X Sintomas que significam que NÃO está indo bem', 'Junho'),
  ('X Sinais que NÃO significam "tá tudo bem"', 'Junho'),
  ('X Perguntas que você DEVE FAZER sobre suas válvulas', 'Banco'),
  ('Qual a diferença entre "traços" e "jato leve"? Quando isso faz diferença?', 'Banco'),
  ('"Erros comuns em válvula": confundir "leve" com "não precisa acompanhar", usar exame isolado...', 'Junho'),
  ('"Verdadeiro ou falso" sobre válvulas. Tanto versão leigo quanto especialista', 'Banco'),
  ('"Nesse caso, você prefere: X versus Y" - formato enquete. Cx versus percutâneo, 3D x Strain...', 'Banco'),
  ('X Sinais de Estenose Aórtica que você não pode ignorar', 'Junho'),
  ('Estenose Aórtica sem sintomas existe? TAVI já? Ou dá pra esperar?', 'Junho'),
  ('TAVI versus Cirurgia: como se decide?', 'Junho'),
  ('Os principais tratamentos da Estenose Aórtica', 'Banco'),
  ('Você é um dos 2% da população que tem VAB? O que é isso e por que isso importa?', 'Julho'),
  ('Tratamento preventivo para VAB em jovens: isso já é uma realidade?', 'Banco'),
  ('TAVI na Insuficiência Aórtica: inovação ou extrapolação?', 'Banco'),
  ('Como a sua valva aórtica tem que ser? (anatomia, fisiologia)', 'Banco'),
  ('O Eco consegue ver bem a sua valva aórtica? (imagem Eco versus in vivo, na cirurgia)', 'Julho'),
  ('Prolapso da valva mitral: qual a chance de você ter? E de ter que corrigir?', 'Banco'),
  ('A diferença entre um prolapso "bom" e um "ruim"', 'Banco'),
  ('Você já ouviu um sopro cardíaco? (definição e exemplos de sons de diversos sopros)', 'Julho'),
  ('O que procedimentos dentários e válvulas têm em comum?', 'Julho'),
  ('Quem se beneficia do TEER?', 'Banco'),
  ('IM degenerativa versus funcional: não é tudo a mesma coisa!', 'Banco'),
  ('Você consegue dizer a gravidade dessa IM/EM só pelo sopro?', 'Banco'),
  ('Quando podemos dizer que os sintomas do paciente são por causa da tricúspide?', 'Julho'),
  ('Sinais de que você têm regurgitação tricúspide (e o que fazer nesses casos)', 'Julho'),
  ('Intervenções percutâneas na tricúspide? Isso já existe?', 'Banco'),
  ('Implante valvar tricúspide (Lux Valve) - como funciona?', 'Banco'),
  ('O que faz o Eco da tricúspide ser desafiador?', 'Banco'),
  ('Imagem da aorta: quando que o Eco basta e quando pedir uma TC/RM?', 'Banco'),
  ('Sopro na região da valva pulmonar: o que pode ser?', 'Banco'),
  ('Válvula pulmonar no adulto: quando ela se torna importante?', 'Banco'),
  ('O que faz da endocardite infecciosa uma urgência diagnóstica', 'Julho'),
  ('Qual o risco real de você ter endocardite?', 'Julho'),
  ('As principais indicações de profilaxia de endocardite (e quando NÃO fazer!)', 'Banco'),
  ('Onde está a endocardite faz a diferença pro tratamento?', 'Banco'),
  ('Vou precisar de cirurgia de troca valvar. E agora, mecânica ou biológica?', 'Agosto'),
  ('Toda prótese valvar precisa de anticoagulantes?', 'Agosto'),
  ('A vantagem de ter alguém experiente no Eco intraoperatório da sua cirurgia', 'Banco'),
  ('Quanto tempo duram as próteses valvares? Como eu sei a hora de trocar?', 'Banco'),
  ('Sinais de que sua prótese valvar está degenerada', 'Banco'),
  ('Valve-in-valve: uma opção cada vez mais utilizada', 'Agosto'),
  ('O que você precisa saber sobre anticoagulação para próteses valvares', 'Banco'),
  ('Como a febre reumática vira doença valvar? E como prevenir?', 'Banco'),
  ('Como tratar a Estenose Mitral Reumática?', 'Banco'),
  ('Gestação e valvopatias: o que precisa estar "ok" antes de engravidar?', 'Agosto'),
  ('Desafios do manejo das valvopatias na gestante', 'Banco'),
  ('O acontece durante uma troca valvar cirúrgica?', 'Agosto'),
  ('Plastia ou troca valvar? - uma decisão a ser discutida em equipe', 'Banco'),
  ('O que monitoramos após uma cirurgia de troca valvar?', 'Agosto'),
  ('O que ficar de olho no seu familiar que fez uma cirurgia cardíaca?', 'Banco'),
  ('EcoTT versus EcoTE - quando cada um é necessário?', 'Banco'),
  ('Como o Eco 3D pode ser fundamental para o seu coração', 'Banco'),
  ('Strain: você sabe indicar e interpretar?', 'Banco'),
  ('Você sabe como funciona o ecocardiograma?', 'Agosto'),
  ('Essas imagens de Eco 3D fizeram a diferença para o desfecho do paciente!', 'Banco'),
  ('As utilidades da Tomografia Cardíaca nas valvopatias', 'Banco'),
  ('Você sabe o papel da Tomografia Cardíaca no preparo da TAVI?', 'Agosto'),
  ('A RM Cardíaca faz diferença na avaliação de valvopatias?', 'Banco'),
  ('Sizing para TAVI: por que saber QUEM faz o sizing faz a diferença?', 'Banco'),
  ('Falta de ar, cansaço, inchaço... Como identificar sinais de alerta nesses casos?', 'Setembro'),
  ('Síncope pode ocorrer por causa das válvulas?', 'Setembro'),
  ('Sinais para ficar de olho no seu familiar com valvopatia!', 'Banco'),
  ('O meu smartwatch pode me ajudar a no acompanhamento de valvopatias?', 'Setembro'),
  ('IA na imagem cardíaca: quando ela ajuda? E quando ainda não?', 'Setembro'),
  ('Novos dispositivos para tratamento de valvopatias: como funcionam?', 'Agosto'),
  ('Veja como uma TAVI é aberta!', 'Banco'),
  ('É FOP ou CIA? Qual a diferença?', 'Setembro'),
  ('Ter FOP significa que vou ter que fechar?', 'Banco'),
  ('Como é feito o fechamento de um FOP?', 'Banco'),
  ('Os riscos que uma CIA pode trazer ao seu coração', 'Banco'),
  ('Sopro cardíaco é sinônimo de problema. Mito ou verdade?', 'Banco'),
  ('TAVI é só para pacientes idosos. Mito ou verdade?', 'Setembro'),
  ('Quais as diferenças entre os métodos de TEER? (MitraClip versus Pascal)', 'Banco'),
  ('Qual a vantagem de se fazer uma troca valvar percutânea?', 'Setembro'),
  ('Mitos sobre valvopatias que você precisa conhecer', 'Setembro'),
  ('"Tricúspide não tem como tratar" - estamos em 2026. Será que ainda é assim?', 'Banco'),
  ('As próteses valvares duram para sempre?', 'Banco'),
  ('O que você deve levar para sua avaliação cardiológica?', 'Banco'),
  ('De quanto em quanto tempo eu tenho que acompanhar minha doença valvar?', 'Banco'),
  ('Vacinas importantes que protegem inclusive o seu coração!', 'Setembro'),
  ('Por que seus hábitos de higiene bucal podem proteger (ou danificar) o seu coração', 'Setembro'),
  ('Pós-procedimento valvar: 5 cuidados, da primeira semana ao primeiro mês', 'Outubro'),
  ('Medicamentos que nós, especialistas em valvopatias, não vivemos sem', 'Banco'),
  ('Piora súbita dos sintomas após procedimento/cirurgia: o que fazer?', 'Outubro'),
  ('Valvopatias discretas - e agora? Por quanto tempo eu preciso acompanhar?', 'Outubro'),
  ('Minha IM era grave e agora é moderada. Como isso aconteceu? (diferenças de laudos, tempo...)', 'Banco'),
  ('Posso fazer atividade física se tenho valvopatia?', 'Banco'),
  ('Perguntas importantes a se fazer antes de um procedimento cardíaco', 'Outubro'),
  ('Quais sintomas são normais após uma cirurgia cardíaca?', 'Banco'),
  ('O que significa aparecer um sopro no pós operatório?', 'Outubro'),
  ('Do sintoma ao pós: nosso acompanhamento valvar é integral', 'Outubro'),
  ('Sua doença valvar merece um PLANO de cuidado (enaltecer longitudinalidade do serviço)', 'Banco'),
  ('Um Heart Team focado em valvopatias - decisões mais seguras para casos complexos', 'Outubro'),
  ('Segunda opinião em valvopatias: traga maior segurança para seu paciente!', 'Outubro'),
  ('Por que válvula tem que ser no Valve Care Center?', 'Novembro'),
  ('Avaliação especializada antes, durante e após a sua TAVI!', 'Novembro'),
  ('Quem somos? - Valve Care Center', 'Banco'),
  ('Profissionais experientes atuando JUNTOS - como um Heart Team pode transformar sua saúde?', 'Novembro'),
  ('Nosso grupo é único! - Solicite uma segunda opinião em valvopatias', 'Banco'),
  ('Comunicação clara com o paciente - você sabe o que tem e o que vai fazer', 'Banco'),
  ('Sem idas e vindas desnecessárias - organização para quem vem de fora de Curitiba', 'Banco'),
  ('Ecocardiograma avançado disponível sempre que necessário - 3D/Strain/Transesofágico', 'Outubro'),
  ('Experiências nos maiores centros do Brasil, juntas num centro perto de você!', 'Novembro'),
  ('O que a gente não negocia: segurança, clareza e humanidade', 'Novembro'),
  ('Acompanhar a JORNADA (e não apenas o procedimento) é um motivo de ORGULHO para nós!', 'Dezembro'),
  ('Consulta valvar: agende já! (presencial ou online)', 'Dezembro'),
  ('Precisa de uma segunda opinião para doenças valvares? Marque já pelo link na bio!', 'Novembro'),
  ('Faça seu Ecocardiograma Avançado conosco!', 'Banco'),
  ('Vai fazer TAVI ou TEER? Marque uma avaliação conosco!', 'Novembro'),
  ('Acompanhe sua prótese valvar conosco!', 'Dezembro'),
  ('Fecho ou não fecho meu FOP? - Agende uma avaliação conosco!', 'Dezembro'),
  ('Doenças valvares podem ser silenciosas - não é apenas o sintoma que marca o risco!', 'Banco'),
  ('"Assintomático" não é o mesmo que "sem progressão" - acompanhe sua doença valvar!', 'Dezembro'),
  ('Como funciona nossa segunda opinião em valvopatias?', 'Dezembro'),
  ('Quando que acompanhamento clínico é mais indicado do que intervir?', 'Banco'),
  ('O que é uma indicação? Por que ninguém "empurra" intervenções', 'Banco'),
  ('Foco em válvulas complementa (e não compete): como podemos agregar à sua saúde?', 'Banco'),
  ('Consulta objetiva: o que a gente já resolve no primeiro dia?', 'Banco'),
  ('Teleconsulta em valvopatias: quando ela pode ser uma opção?', 'Dezembro'),
  ('Quais exames levar na minha primeira consulta?', 'Novembro'),
  ('Perguntas frequentes (tema: planos de saúde atendidos, tempo de consulta, custo exames)', 'Banco'),
  ('Depoimentos: "A segunda opinião trouxe mais clareza para meu tratamento!"', 'Novembro'),
  ('Depoimentos: "Foi importante entender o que meu laudo de ecocardiograma dizia!"', 'Dezembro'),
  ('Depoimentos: "Faço tudo em um lugar só!"', 'Banco'),
  ('Depoimentos: "Acompanhei por um tempo e decidimos intervir no momento certo!"', 'Dezembro'),
  ('Depoimentos: "Agora eu sei os sinais que precisava observar no meu familiar"', 'Banco'),
  ('Perguntas que você deve se fazer antes da consulta (formação/experiência do médico/serviço...)', 'Banco'),
  ('Não deixe a avaliação da sua doença valvar para depois (mesmo que assintomática!)', 'Banco');

UPDATE posts p
SET mes = t.mes
FROM tmp_vcc_meses_2026 t
WHERE p.cliente_id = 'eb9aa951-b915-4b09-9c34-072b56afe4e0'::uuid
  AND p.titulo = t.titulo;

COMMIT;
